---
title: "phase1"
output: html_document
---

```{r}
library(ggplot2)
library(data.table)
library(magrittr) 
library(tidyr)
library(ggrepel)
library(GGally)
library(pheatmap)
```


```{r}
  case_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/Case.csv")
  patientInfo_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/PatientInfo.csv")
  policy_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/Policy.csv")
  region_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/Region.csv")
  searchTrend_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/SearchTrend.csv")
  seoulFloating_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/SeoulFloating.csv")
  time_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/Time.csv")
  timeAge_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/TimeAge.csv")
  timeGender_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/TimeGender.csv")
  timeProvince_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/TimeProvince.csv")
  weather_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/Weather.csv")
  krx100_dt <- fread("~/Desktop/tum ws20/R/case_study_data/data/KRX100.csv")
```

```{r}
#data_wrangling_tidying
searchTrend_dt <- melt(searchTrend_dt, id.vars = "date", value.name = "search_metric", variable.name = "search_keyword")

#krx100_dt
krx100_dt[,Price := sub(',','',krx100_dt$Price)]
krx100_dt[,Open := sub(',','',krx100_dt$Open)]
krx100_dt[,High := sub(',','',krx100_dt$High)]
krx100_dt[,Low := sub(',','',krx100_dt$Low)]
krx100_dt[,Vol. := sub('M','',krx100_dt$Vol.)]
krx100_dt[,Date := as.Date.character(Date,format ='%b %d, %Y' )]
krx100_dt[,c("Price","Open","High","Low","Vol.") := lapply(.SD, as.double), .SDcols = c("Price","Open","High","Low","Vol.")]
krx100_dt[,`Change %` := NULL]
```



```{r}
#SearchTrends vs Coronavirus Number of Tests
searchTrend_dt[date >= as.Date("2019-12-01") ] %>% ggplot(aes(x= date,y= search_metric)) + geom_line(aes(color=search_keyword)) + geom_line(data = time_dt, aes(x=date, y=test)) + scale_y_log10()
```

```{r}
#Policy$type vs. query_frequency
merge(policy_dt,searchTrend_dt[date >= as.Date("2019-12-01") ], by.x="start_date", by.y="date",all.y = TRUE) %>% ggplot(.,aes(x= start_date,y= search_metric)) + geom_line(aes(color=search_keyword))  + facet_wrap(~type) + scale_y_log10() + geom_point(data = policy_dt,aes(x=start_date, y=5, alpha=0.001))
#Outcome: Only Alert policies ignited web searches for "coronavirus."


merge(policy_dt,searchTrend_dt[date >= as.Date("2019-12-01") & search_keyword == "coronavirus"], by.x="start_date", by.y="date",all.y = TRUE) %>% ggplot(aes(x= start_date,y= search_metric)) + geom_line(aes(linetype=search_keyword))+ scale_y_log10() + geom_point(data = merge(policy_dt,searchTrend_dt[date >= as.Date("2019-12-01") & search_keyword == "coronavirus" ], by.x="start_date", by.y="date",all.x = TRUE), aes(x=start_date, y=search_metric, color = type))
#Outcome: Even Alert type policies are uncorrelated to the web queries. They don't ignite.

```

```{r}
#korean_stock_market_performance vs. case numbers
krx100_dt
merge(krx100_dt,time_dt, by.x = 'Date', by.y = 'date') %>% ggplot(aes(x=confirmed, y= Price, color = Date, size = Vol., alpha = 0.05)) + geom_point()

#inferences
#1. outbreak has pushed trading volumes. financial markets became hot.(Prior to March, are the lowest volume of all months)
#2. markets adapted coronavirus cases by time. During March, ~8000 cases was enough to far the market to see ~3500 price points. However by time, markets saw above ~4500 price points with +12000 cases.
#3. trading volume decreased as we approach July 2020. 


```

```{r}
#stock market vs. query_trends
merge(krx100_dt, searchTrend_dt, by.x='Date', by.y= 'date')[search_keyword == "coronavirus"] %>% ggplot(aes(x = Price, y= scale(search_metric), size = Vol., alpha = 0.001)) + geom_point() + scale_x_log10()


market_metric_mat <- merge(krx100_dt, searchTrend_dt, by.x='Date', by.y= 'date')[search_keyword == "coronavirus",c(2,8)] %>% as.matrix()
rownames(market_metric_mat) <- merge(krx100_dt, searchTrend_dt, by.x='Date', by.y= 'date')[search_keyword == "coronavirus",Date]
pheatmap(market_metric_mat,cluster_rows = F,cluster_cols = F, scale="column",show_rownames = FALSE)


merge(krx100_dt, searchTrend_dt, by.x='Date', by.y= 'date')[search_keyword == "coronavirus"] %>% ggplot(aes(x=Date,y=scale(Price))) + geom_line(aes(color="KRX100 Market Value(Scaled)")) + geom_line(aes(x=Date, y=scale(search_metric), color="web queries for -coronavirus-")) + scale_color_discrete(name = "Line")
```

```{r}
#stock_market_performance vs. cases in provinces

merge(timeProvince_dt, krx100_dt, by.x='date', by.y='Date')%>% ggplot(aes(x=date,y=scale(Price))) + geom_line() + geom_line(aes(x=date,y=scale(confirmed))) +  facet_wrap(~province)
```

```{r}
# policies vs stock_market_reaction
ggplot(krx100_dt, aes(x=Date, y=Price)) + geom_line() + geom_point(data = merge(krx100_dt, policy_dt, by.x= "Date", by.y ="start_date"), aes(x=Date,y=Price,color=type))

#interpretation
#1.transformation measures helped to contain the spread.

```

